/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.uwaterloo.subletr.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param passwordOld 
 * @param passwordNew 
 */


data class ChangePasswordUserRequest (

    @Json(name = "password_old")
    val passwordOld: kotlin.String,

    @Json(name = "password_new")
    val passwordNew: kotlin.String

)

