/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.uwaterloo.subletr.api.models

import org.uwaterloo.subletr.api.models.ResidenceType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param addressLine 
 * @param addressCity 
 * @param addressPostalcode 
 * @param addressCountry 
 * @param price 
 * @param rooms 
 * @param leaseStart 
 * @param leaseEnd 
 * @param description 
 * @param imgIds 
 * @param residenceType 
 */


data class CreateListingRequest (

    @Json(name = "address_line")
    val addressLine: kotlin.String,

    @Json(name = "address_city")
    val addressCity: kotlin.String,

    @Json(name = "address_postalcode")
    val addressPostalcode: kotlin.String,

    @Json(name = "address_country")
    val addressCountry: kotlin.String,

    @Json(name = "price")
    val price: kotlin.Int,

    @Json(name = "rooms")
    val rooms: kotlin.Int,

    @Json(name = "lease_start")
    val leaseStart: kotlin.String,

    @Json(name = "lease_end")
    val leaseEnd: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "img_ids")
    val imgIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "residence_type")
    val residenceType: ResidenceType

)

