/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.uwaterloo.subletr.api.models

import org.uwaterloo.subletr.api.models.ResidenceType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param price 
 * @param roomsAvailable 
 * @param roomsTotal 
 * @param bathroomsAvailable 
 * @param bathroomsEnsuite 
 * @param bathroomsTotal 
 * @param leaseStart 
 * @param leaseEnd 
 * @param description 
 * @param residenceType 
 * @param gender 
 */


data class UpdateListingRequest (

    @Json(name = "price")
    val price: kotlin.Int? = null,

    @Json(name = "rooms_available")
    val roomsAvailable: kotlin.Int? = null,

    @Json(name = "rooms_total")
    val roomsTotal: kotlin.Int? = null,

    @Json(name = "bathrooms_available")
    val bathroomsAvailable: kotlin.Int? = null,

    @Json(name = "bathrooms_ensuite")
    val bathroomsEnsuite: kotlin.Int? = null,

    @Json(name = "bathrooms_total")
    val bathroomsTotal: kotlin.Int? = null,

    @Json(name = "lease_start")
    val leaseStart: kotlin.String? = null,

    @Json(name = "lease_end")
    val leaseEnd: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "residence_type")
    val residenceType: ResidenceType? = null,

    @Json(name = "gender")
    val gender: kotlin.String? = null

)

