// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/login.proto

package org.uwaterloo.subletr.proto.auth;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_UserLoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_UserLoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_UserLoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_UserLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020auth/login.proto\022\004auth\"3\n\020UserLoginReq" +
      "uest\022\r\n\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"\"\n" +
      "\021UserLoginResponse\022\r\n\005token\030\001 \001(\tB$\n org" +
      ".uwaterloo.subletr.proto.authP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_auth_UserLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_UserLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_UserLoginRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_auth_UserLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_UserLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_UserLoginResponse_descriptor,
        new java.lang.String[] { "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
