// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/login.proto

package org.uwaterloo.subletr.proto.auth;

public interface UserLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.uwaterloo.subletr.proto.auth.UserLoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
