//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/login.proto

package org.uwaterloo.subletr.proto.auth;

@kotlin.jvm.JvmName("-initializeuserLoginResponse")
public inline fun userLoginResponse(block: org.uwaterloo.subletr.proto.auth.UserLoginResponseKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.auth.UserLoginResponse =
  org.uwaterloo.subletr.proto.auth.UserLoginResponseKt.Dsl._create(org.uwaterloo.subletr.proto.auth.UserLoginResponse.newBuilder()).apply { block() }._build()
public object UserLoginResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.uwaterloo.subletr.proto.auth.UserLoginResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.uwaterloo.subletr.proto.auth.UserLoginResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.uwaterloo.subletr.proto.auth.UserLoginResponse = _builder.build()

    /**
     * <code>string token = 1;</code>
     */
    public var token: kotlin.String
      @JvmName("getToken")
      get() = _builder.getToken()
      @JvmName("setToken")
      set(value) {
        _builder.setToken(value)
      }
    /**
     * <code>string token = 1;</code>
     */
    public fun clearToken() {
      _builder.clearToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.uwaterloo.subletr.proto.auth.UserLoginResponse.copy(block: org.uwaterloo.subletr.proto.auth.UserLoginResponseKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.auth.UserLoginResponse =
  org.uwaterloo.subletr.proto.auth.UserLoginResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

