//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: auth/login.proto

package org.uwaterloo.subletr.proto.auth;

@kotlin.jvm.JvmName("-initializeuserLoginRequest")
public inline fun userLoginRequest(block: org.uwaterloo.subletr.proto.auth.UserLoginRequestKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.auth.UserLoginRequest =
  org.uwaterloo.subletr.proto.auth.UserLoginRequestKt.Dsl._create(org.uwaterloo.subletr.proto.auth.UserLoginRequest.newBuilder()).apply { block() }._build()
public object UserLoginRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.uwaterloo.subletr.proto.auth.UserLoginRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.uwaterloo.subletr.proto.auth.UserLoginRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.uwaterloo.subletr.proto.auth.UserLoginRequest = _builder.build()

    /**
     * <code>string email = 1;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 1;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * <code>string password = 2;</code>
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 2;</code>
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.uwaterloo.subletr.proto.auth.UserLoginRequest.copy(block: org.uwaterloo.subletr.proto.auth.UserLoginRequestKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.auth.UserLoginRequest =
  org.uwaterloo.subletr.proto.auth.UserLoginRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

