// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth/login.proto

package org.uwaterloo.subletr.proto.auth;

public interface UserLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.uwaterloo.subletr.proto.auth.UserLoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
