//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user/create.proto

package org.uwaterloo.subletr.proto.user;

@kotlin.jvm.JvmName("-initializecreateUserResponse")
public inline fun createUserResponse(block: org.uwaterloo.subletr.proto.user.CreateUserResponseKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.user.CreateUserResponse =
  org.uwaterloo.subletr.proto.user.CreateUserResponseKt.Dsl._create(org.uwaterloo.subletr.proto.user.CreateUserResponse.newBuilder()).apply { block() }._build()
public object CreateUserResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.uwaterloo.subletr.proto.user.CreateUserResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.uwaterloo.subletr.proto.user.CreateUserResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.uwaterloo.subletr.proto.user.CreateUserResponse = _builder.build()

    /**
     * <code>int64 user_id = 1;</code>
     */
    public var userId: kotlin.Long
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>int64 user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.uwaterloo.subletr.proto.user.CreateUserResponse.copy(block: org.uwaterloo.subletr.proto.user.CreateUserResponseKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.user.CreateUserResponse =
  org.uwaterloo.subletr.proto.user.CreateUserResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

