// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/create.proto

package org.uwaterloo.subletr.proto.user;

public interface CreateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.CreateUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
