//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user/create.proto

package org.uwaterloo.subletr.proto.user;

@kotlin.jvm.JvmName("-initializecreateUserRequest")
public inline fun createUserRequest(block: org.uwaterloo.subletr.proto.user.CreateUserRequestKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.user.CreateUserRequest =
  org.uwaterloo.subletr.proto.user.CreateUserRequestKt.Dsl._create(org.uwaterloo.subletr.proto.user.CreateUserRequest.newBuilder()).apply { block() }._build()
public object CreateUserRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: org.uwaterloo.subletr.proto.user.CreateUserRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: org.uwaterloo.subletr.proto.user.CreateUserRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): org.uwaterloo.subletr.proto.user.CreateUserRequest = _builder.build()

    /**
     * <code>string first_name = 1;</code>
     */
    public var firstName: kotlin.String
      @JvmName("getFirstName")
      get() = _builder.getFirstName()
      @JvmName("setFirstName")
      set(value) {
        _builder.setFirstName(value)
      }
    /**
     * <code>string first_name = 1;</code>
     */
    public fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * <code>string last_name = 2;</code>
     */
    public var lastName: kotlin.String
      @JvmName("getLastName")
      get() = _builder.getLastName()
      @JvmName("setLastName")
      set(value) {
        _builder.setLastName(value)
      }
    /**
     * <code>string last_name = 2;</code>
     */
    public fun clearLastName() {
      _builder.clearLastName()
    }

    /**
     * <code>string email = 3;</code>
     */
    public var email: kotlin.String
      @JvmName("getEmail")
      get() = _builder.getEmail()
      @JvmName("setEmail")
      set(value) {
        _builder.setEmail(value)
      }
    /**
     * <code>string email = 3;</code>
     */
    public fun clearEmail() {
      _builder.clearEmail()
    }

    /**
     * <code>string password = 4;</code>
     */
    public var password: kotlin.String
      @JvmName("getPassword")
      get() = _builder.getPassword()
      @JvmName("setPassword")
      set(value) {
        _builder.setPassword(value)
      }
    /**
     * <code>string password = 4;</code>
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * <code>string gender = 5;</code>
     */
    public var gender: kotlin.String
      @JvmName("getGender")
      get() = _builder.getGender()
      @JvmName("setGender")
      set(value) {
        _builder.setGender(value)
      }
    /**
     * <code>string gender = 5;</code>
     */
    public fun clearGender() {
      _builder.clearGender()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun org.uwaterloo.subletr.proto.user.CreateUserRequest.copy(block: org.uwaterloo.subletr.proto.user.CreateUserRequestKt.Dsl.() -> kotlin.Unit): org.uwaterloo.subletr.proto.user.CreateUserRequest =
  org.uwaterloo.subletr.proto.user.CreateUserRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

