//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: user/create.proto

package user;

@kotlin.jvm.JvmName("-initializecreateUserResponse")
public inline fun createUserResponse(block: user.CreateUserResponseKt.Dsl.() -> kotlin.Unit): user.Create.CreateUserResponse =
  user.CreateUserResponseKt.Dsl._create(user.Create.CreateUserResponse.newBuilder()).apply { block() }._build()
public object CreateUserResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: user.Create.CreateUserResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: user.Create.CreateUserResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): user.Create.CreateUserResponse = _builder.build()

    /**
     * <code>int64 user_id = 1;</code>
     */
    public var userId: kotlin.Long
      @JvmName("getUserId")
      get() = _builder.getUserId()
      @JvmName("setUserId")
      set(value) {
        _builder.setUserId(value)
      }
    /**
     * <code>int64 user_id = 1;</code>
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun user.Create.CreateUserResponse.copy(block: user.CreateUserResponseKt.Dsl.() -> kotlin.Unit): user.Create.CreateUserResponse =
  user.CreateUserResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

