#!/usr/bin/env bash

set -e

KOTLIN_MAIN_DIR="android/app/src/main/java"
KOTLIN_PROTO_DIR="$KOTLIN_MAIN_DIR/org/uwaterloo/subletr/proto"

cd $(git rev-parse --show-toplevel)

rm -rf $KOTLIN_PROTO_DIR

mkdir -p $KOTLIN_PROTO_DIR

protoc -Iprotos --java_out="$KOTLIN_MAIN_DIR" --kotlin_out="$KOTLIN_MAIN_DIR" $(find "protos" -name "*.proto" | xargs)

